# Book settings
title: Enriching Digital Heritage with LLMs and Linked Open Data
author:
execute:
  execute_notebooks: 'off'
parse:
  myst_extended_syntax: true
# Information about where the book exists on the web
repository:
  url: https://github.com/pelagios/llm-lod-enriching-heritage
  branch: main
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: false
launch_buttons:
  colab_url: "https://colab.research.google.com"
