name: Sync intro.md -> README.md (all folders)

on:
  workflow_dispatch:
  push:
    paths:
      - '**/intro.md'
    branches:
      - main  # <-- adjust to your default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug: show branch, tree, and any intro.md
        shell: bash
        run: |
          set -euxo pipefail
          echo "REF: $GITHUB_REF  SHA: $GITHUB_SHA"
          echo "Checked-out branch (may be detached HEAD):"
          git branch --show-current || true
          pwd
          ls -la
          echo "Tracked intro.md via git:"
          git ls-files '**/intro.md' || true
          echo "All intro.md via find:"
          find . -type f -name 'intro.md' -print || true

      - name: Copy intro.md to README.md alongside each file
        shell: bash
        run: |
          set -euo pipefail
          mapfile -t files < <(find . -type f -name 'intro.md' -print)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No intro.md files found anywhere."
            exit 0
          fi

          for f in "${files[@]}"; do
            dir="$(dirname "$f")"
            dest="$dir/README.md"
            echo "Syncing: $f -> $dest"
            cp "$f" "$dest"
            git add "$dest"
          done

      - name: Commit if staged changes exist
        shell: bash
        run: |
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Sync README.md files from intro.md"
          git push

